In [1]:
CONSTRAINT_TOOLS = '/scratch/ucgd/lustre-work/quinlan/u6018199/constraint-tools'
CONSTRAINT_TOOLS_DATA = '/scratch/ucgd/lustre-work/quinlan/data-shared/constraint-tools'

import numpy as np 

import sys
sys.path.append(f'{CONSTRAINT_TOOLS}/utilities')

from ravel_unravel import ravel, unravel

def test_ravel():
  print('######### test ravel ############')
  sequences = np.array([['A','B'], ['C','D'], ['E','F'], ['G','H']]) # 4 alleles, 2 sites
  print('sequences:')
  print(sequences)
  print(sequences.shape)

  sequences_raveled = ravel(sequences)
  print('raveled sequences:')
  print(sequences_raveled)
  print(sequences_raveled.shape)

  comparison = sequences_raveled == ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
  assert comparison.all()

test_ravel() 

def test_unravel(): 
  print('######### test unravel ############')
  embeddings = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15],
    [16,17,18],
    [19,20,21],
    [22,23,24]
  ]
  embeddings = np.array(embeddings) 
  print('embeddings:')
  print(embeddings)
  print(embeddings.shape)

  embeddings_unraveled = unravel(embeddings, number_alleles=4, number_sites=2)
  print('unraveled embeddings:')
  print(embeddings_unraveled)
  print(embeddings_unraveled.shape)

  comparison = embeddings_unraveled == np.array([
    [[ 1,  2,  3], [ 4,  5,  6]],
    [[ 7,  8,  9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24]]
  ])
  assert comparison.all()

test_unravel()


######### test ravel ############
sequences:
[['A' 'B']
 ['C' 'D']
 ['E' 'F']
 ['G' 'H']]
(4, 2)
raveled sequences:
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H']
(8,)
######### test unravel ############
embeddings:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]
(8, 3)
unraveled embeddings:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
(4, 2, 3)
